# This dockerfile shows how to install the C++ OpenTDF library, and then perform a
# `go build` on Go dependencies that need that C++ library.
#
# The `client-cpp` library binary and include files MUST be available to Go
# during any `go build` step.
#
# As `client-cpp` uses `conan` for install/build/deploy, we rely on that to build `client-cpp` for us for
# targeted platforms, and install any necessary C++ deps that are required.

FROM python:3.9-bullseye AS builder

# Get the argument values
ARG VCONAN_VER
ARG VCONAN_BRANCH_VERSION
ARG VCONAN_RECIPE_VER
ARG VCLIENT_CPP_VER

WORKDIR /build

RUN apt-get update && apt-get install -y cmake
RUN pip install conan==${VCONAN_VER}

RUN git clone -b ${VCONAN_RECIPE_VER} 'https://github.com/opentdf/client-conan.git'

WORKDIR client-conan

RUN conan create recipe/all opentdf-client/${VCLIENT_CPP_VER}@ -pr:b=default --build=opentdf-client --build=missing -o opentdf-client:branch_version=${VCONAN_BRANCH_VERSION}

FROM golang:1.19-bullseye

WORKDIR /build

COPY --chown=0:0 --from=builder /root/.conan/data/opentdf-client/1.5.0/_/_/package/*/lib /build/tdf-client/lib
COPY --chown=0:0 --from=builder /root/.conan/data/opentdf-client/1.5.0/_/_/package/*/include /build/tdf-client/include

ENV GO111MODULE=on \
    CGO_ENABLED=1 \
    GOOS=linux \
    CGO_LDFLAGS="-L/build/tdf-client/lib" \
    CGO_CFLAGS="-I/build/tdf-client/include"

COPY . .

# Let's create a /dist folder containing just the files necessary for runtime.
# Later, it will be copied as the / (root) of the output image.
RUN mkdir /dist

#Build the demo executable - can be skipped if not needed
RUN go build  -o /dist/wrappertest ./cmd/wrappertest

# Build the library - Library consumers will build this library implicitly as part of
# `go get -u github.com/opentdf/client-go` (assuming CGO_CFLAGS and CGO_LDFLAGS point
# at the correct C++ headers/static lib in that environment, for that environment)
# but doing it explicitly here as well for the sake of example
RUN go build -o /dist/client-go
